"""
explorar_erro_reprojecao.py
===========================
Read and visualize .npy reprojection error files generated by the
freemocap triangulation pipeline using the AprilTag detector.

Each AprilTag contributes up to 5 points (mode 'both'):
    tag{id}_center, tag{id}_corner0, tag{id}_corner1, tag{id}_corner2, tag{id}_corner3

Usage:
    python explorar_erro_reprojecao.py --path /path/to/session/output_data/raw_data
    python explorar_erro_reprojecao.py --path . --tag_ids 0 1 2 3 --point_mode both
    python explorar_erro_reprojecao.py --path . --no_plots
"""

import argparse
import sys
from pathlib import Path

import numpy as np

try:
    import matplotlib.pyplot as plt
    import matplotlib.gridspec as gridspec
    HAS_MPL = True
except ImportError:
    HAS_MPL = False
    print("[aviso] matplotlib não encontrado — modo texto apenas.\n"
          "        Instale com: pip install matplotlib\n")


# ────────────────────────────────────────────────────────────────────
# Geração de nomes de pontos AprilTag
# ────────────────────────────────────────────────────────────────────

def gerar_nomes_apriltag(tag_ids, point_mode="both"):
    """
    Retorna a lista de nomes dos pontos no mesmo ordering do pipeline.
    point_mode: 'corners' | 'center' | 'both'
    """
    names = []
    for tag_id in tag_ids:
        if point_mode in ("center", "both"):
            names.append(f"tag{tag_id}_center")
        if point_mode in ("corners", "both"):
            for c in range(4):
                names.append(f"tag{tag_id}_corner{c}")
    return names


def inferir_point_mode(n_pontos, n_tags):
    """Infere o point_mode a partir do shape dos dados."""
    if n_pontos == n_tags * 5:
        return "both"
    elif n_pontos == n_tags * 4:
        return "corners"
    elif n_pontos == n_tags:
        return "center"
    return "both"  # fallback


# ────────────────────────────────────────────────────────────────────
# Busca de arquivos
# ────────────────────────────────────────────────────────────────────

def encontrar_arquivos_npy(pasta: Path):
    arquivos = list(pasta.glob("*.npy"))
    if not arquivos:
        print(f"[erro] Nenhum arquivo .npy encontrado em: {pasta}")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"Pasta: {pasta}")
    print(f"{'='*60}")
    print(f"Arquivos .npy encontrados ({len(arquivos)}):")
    for i, f in enumerate(arquivos):
        size_kb = f.stat().st_size / 1024
        print(f"  [{i}] {f.name}  ({size_kb:.1f} KB)")
    print()

    arquivo_medio = None
    arquivo_completo = None
    for f in arquivos:
        name = f.name
        if "numCams_numFrames" in name and "reprojectionError" in name:
            arquivo_completo = f
        elif "numFrames_numTrackedPoints_reprojectionError" in name and "numCams" not in name:
            arquivo_medio = f
    return arquivo_medio, arquivo_completo, arquivos


# ────────────────────────────────────────────────────────────────────
# Análise em texto
# ────────────────────────────────────────────────────────────────────

def resumo_array(arr: np.ndarray, nome: str):
    validos = arr[~np.isnan(arr)]
    print(f"\n── {nome} ──")
    print(f"  Shape:    {arr.shape}")
    print(f"  Dtype:    {arr.dtype}")
    print(f"  Válidos:  {len(validos):,} de {arr.size:,} "
          f"({100*len(validos)/arr.size:.1f}%)")
    if len(validos) > 0:
        print(f"  Mínimo:   {validos.min():.4f} px")
        print(f"  Mediana:  {np.median(validos):.4f} px")
        print(f"  Média:    {validos.mean():.4f} px")
        print(f"  Máximo:   {validos.max():.4f} px")
        pcts = np.percentile(validos, [25, 50, 75, 90, 95, 99])
        print(f"  P25/P50/P75/P90/P95/P99: "
              f"{pcts[0]:.2f} / {pcts[1]:.2f} / {pcts[2]:.2f} / "
              f"{pcts[3]:.2f} / {pcts[4]:.2f} / {pcts[5]:.2f} px")


def analise_por_camera(erro_cam_fr_pt: np.ndarray):
    n_cams = erro_cam_fr_pt.shape[0]
    print(f"\n── Erro médio por câmera ──")
    for c in range(n_cams):
        vals = erro_cam_fr_pt[c][~np.isnan(erro_cam_fr_pt[c])]
        if len(vals) > 0:
            print(f"  Câmera {c}: {vals.mean():.3f} px  "
                  f"(mediana {np.median(vals):.3f} px, max {vals.max():.3f} px)")
        else:
            print(f"  Câmera {c}: sem dados válidos")


def analise_por_ponto(erro_fr_pt: np.ndarray, nomes_pontos: list, n_top: int = 10):
    n_pontos = erro_fr_pt.shape[1]
    media_por_ponto = np.nanmean(erro_fr_pt, axis=0)

    print(f"\n── Erro médio por ponto AprilTag ──")
    print(f"  Total de pontos: {n_pontos}")

    ordem = np.argsort(media_por_ponto)
    top = min(n_top, n_pontos)

    print(f"\n  {top} pontos com MENOR erro:")
    for idx in ordem[:top]:
        nome = nomes_pontos[idx] if idx < len(nomes_pontos) else f"ponto_{idx}"
        print(f"    {nome:30s}: {media_por_ponto[idx]:.3f} px")

    print(f"\n  {top} pontos com MAIOR erro:")
    for idx in ordem[-top:][::-1]:
        nome = nomes_pontos[idx] if idx < len(nomes_pontos) else f"ponto_{idx}"
        print(f"    {nome:30s}: {media_por_ponto[idx]:.3f} px")


def analise_por_tag(erro_fr_pt: np.ndarray, tag_ids: list, point_mode: str):
    """Agrupa o erro por tag (média dos seus pontos)."""
    print(f"\n── Erro médio por tag ──")
    nomes = gerar_nomes_apriltag(tag_ids, point_mode)
    n_pontos_por_tag = 5 if point_mode == "both" else (4 if point_mode == "corners" else 1)

    for i, tag_id in enumerate(tag_ids):
        start = i * n_pontos_por_tag
        end = start + n_pontos_por_tag
        if end > erro_fr_pt.shape[1]:
            break
        bloco = erro_fr_pt[:, start:end]
        vals = bloco[~np.isnan(bloco)]
        if len(vals) > 0:
            print(f"  Tag {tag_id}: {vals.mean():.3f} px  "
                  f"(mediana {np.median(vals):.3f} px, max {vals.max():.3f} px)")
        else:
            print(f"  Tag {tag_id}: sem dados válidos")


# ────────────────────────────────────────────────────────────────────
# Visualizações
# ────────────────────────────────────────────────────────────────────

def plotar_tudo(erro_fr_pt: np.ndarray,
                erro_cam_fr_pt,
                nomes_pontos: list,
                tag_ids: list,
                titulo_base: str = "FreeMoCap — AprilTag"):

    fig = plt.figure(figsize=(18, 11))
    fig.suptitle(f"{titulo_base} — Erro de Reprojeção", fontsize=14, fontweight="bold")
    gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.38)

    vals = erro_fr_pt[~np.isnan(erro_fr_pt)]
    vmax = np.nanpercentile(vals, 95) if len(vals) > 0 else 10

    # ── 1. Histograma geral ──────────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.hist(vals, bins=80, color="#4A90D9", edgecolor="white", linewidth=0.3)
    ax1.axvline(np.median(vals), color="#E74C3C", linestyle="--",
                label=f"Mediana {np.median(vals):.2f} px")
    ax1.axvline(vals.mean(), color="#F39C12", linestyle="--",
                label=f"Média   {vals.mean():.2f} px")
    ax1.set_xlabel("Erro de reprojeção (pixels)")
    ax1.set_ylabel("Contagem de observações")
    ax1.set_title("Distribuição geral do erro")
    ax1.legend(fontsize=8)

    # ── 2. Erro ao longo do tempo ────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1:])
    media_frame = np.nanmean(erro_fr_pt, axis=1)
    frames = np.arange(len(media_frame))
    ax2.plot(frames, media_frame, linewidth=0.9, color="#4A90D9", label="Média por frame")
    ax2.fill_between(frames,
                     np.nanpercentile(erro_fr_pt, 25, axis=1),
                     np.nanpercentile(erro_fr_pt, 75, axis=1),
                     alpha=0.25, color="#4A90D9", label="P25–P75")
    ax2.set_xlabel("Frame")
    ax2.set_ylabel("Erro médio (pixels)")
    ax2.set_title("Erro de reprojeção ao longo do tempo")
    ax2.legend(fontsize=8)

    # ── 3. Heatmap: frame × ponto AprilTag ──────────────────────────
    ax3 = fig.add_subplot(gs[1, :2])
    step = 1 # Mostra todos os frames
    im = ax3.imshow(
        erro_fr_pt[::step, :].T,
        aspect="auto",
        interpolation="nearest",
        cmap="hot_r",
        vmin=0,
        vmax=vmax,
    )
    plt.colorbar(im, ax=ax3, label="pixels")

    # Rotula eixo Y com os nomes dos pontos (cantos e centros)
    n_pts = erro_fr_pt.shape[1]
    tick_positions = list(range(n_pts))
    tick_labels = nomes_pontos[:n_pts] if nomes_pontos else [str(i) for i in range(n_pts)]
    ax3.set_yticks(tick_positions)
    ax3.set_yticklabels(tick_labels, fontsize=6)

    # Linhas separadoras entre tags
    n_pontos_por_tag = n_pts // len(tag_ids) if tag_ids else None
    if n_pontos_por_tag:
        for i in range(1, len(tag_ids)):
            ax3.axhline(i * n_pontos_por_tag - 0.5, color="cyan", linewidth=0.8, alpha=0.7)

    ax3.set_xlabel("Frame (amostrado)" if step > 1 else "Frame")
    ax3.set_ylabel("Ponto (tag + tipo)")
    ax3.set_title("Heatmap: erro por frame × ponto AprilTag")

    # ── 4. Erro por câmera ───────────────────────────────────────────
    if erro_cam_fr_pt is not None:
        ax4 = fig.add_subplot(gs[1, 2])
        n_cams = erro_cam_fr_pt.shape[0]
        medias_cam = [np.nanmean(erro_cam_fr_pt[c]) for c in range(n_cams)]
        bars = ax4.bar(range(n_cams), medias_cam, color="#4A90D9", edgecolor="white")
        ax4.bar_label(bars, fmt="%.2f px", fontsize=8)
        ax4.set_xlabel("Câmera")
        ax4.set_ylabel("Erro médio (pixels)")
        ax4.set_title("Erro médio por câmera")
        ax4.set_xticks(range(n_cams))
        ax4.set_xticklabels([f"Cam {c}" for c in range(n_cams)])

    plt.savefig("reprojection_error_apriltag.png", dpi=150, bbox_inches="tight")
    print("\n[✓] Gráfico salvo como: reprojection_error_apriltag.png")
    plt.show()


# ────────────────────────────────────────────────────────────────────
# Main
# ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Visualize freemocap reprojection errors with AprilTag detector."
    )
    parser.add_argument("--path", "-p", type=str, default=".",
                        help="Path to the folder with .npy files (e.g. output_data/raw_data)")
    parser.add_argument("--mean_file", "-m", type=str, default=None,
                        help="Direct path to the mean error .npy file")
    parser.add_argument("--full_file", "-f", type=str, default=None,
                        help="Direct path to the by-camera error .npy file")
    parser.add_argument("--tag_ids", nargs="+", type=int, default=[0, 1, 2, 3],
                        help="Tag IDs used (default: 0 1 2 3)")
    parser.add_argument("--point_mode", type=str, default=None,
                        choices=["corners", "center", "both"],
                        help="Point mode: 'corners', 'center' or 'both' (autodetected if omitted)")
    parser.add_argument("--no_plots", action="store_true",
                        help="Only print statistics to terminal, without opening plots")
    args = parser.parse_args()

    session_path = Path(args.path).expanduser().resolve()

    # Load files
    if args.mean_file:
        mean_file = Path(args.mean_file)
        full_file = Path(args.full_file) if args.full_file else None
    else:
        mean_file, full_file, _ = encontrar_arquivos_npy(session_path)

    if mean_file is None:
        print("[error] Could not find the mean error file automatically.")
        print("        Use --mean_file to specify the path.")
        sys.exit(1)

    print(f"\nLoading: {mean_file.name}")
    erro_fr_pt = np.load(mean_file)

    erro_cam_fr_pt = None
    if full_file and full_file.exists():
        print(f"Loading: {full_file.name}")
        erro_cam_fr_pt = np.load(full_file)

    # Infere / valida point_mode
    n_pontos = erro_fr_pt.shape[1]
    n_tags = len(args.tag_ids)
    point_mode = args.point_mode or inferir_point_mode(n_pontos, n_tags)
    nomes_pontos = gerar_nomes_apriltag(args.tag_ids, point_mode)

    print(f"\n  Tags detectadas:   {args.tag_ids}")
    print(f"  Point mode:        {point_mode}")
    print(f"  Total de pontos:   {n_pontos} "
          f"({'OK' if len(nomes_pontos) == n_pontos else f'esperado {len(nomes_pontos)} — verifique --tag_ids e --point_mode'})")

    # Análise
    resumo_array(erro_fr_pt, "Erro médio por frame/ponto [frames, pontos]")

    if erro_cam_fr_pt is not None:
        resumo_array(erro_cam_fr_pt, "Erro por câmera [cameras, frames, pontos]")
        analise_por_camera(erro_cam_fr_pt)

    analise_por_ponto(erro_fr_pt, nomes_pontos, n_top=min(8, n_pontos))
    analise_por_tag(erro_fr_pt, args.tag_ids, point_mode)

    # Visualization
    if not args.no_plots:
        if HAS_MPL:
            plotar_tudo(
                erro_fr_pt=erro_fr_pt,
                erro_cam_fr_pt=erro_cam_fr_pt,
                nomes_pontos=nomes_pontos,
                tag_ids=args.tag_ids,
                titulo_base=session_path.parent.name,
            )
        else:
            print("\n[aviso] Instale matplotlib para ver os gráficos: pip install matplotlib")


if __name__ == "__main__":
    main()
